<div id="help-page">
  <h1>Plugin Help</h1>
  <p>This wordpress plugin is brand new so we are looking to gather feedback from our users. If you are having problems using the Plugin, please take a moment to submit a ticket and let us know what problems you are running into.</p>
  <p><a href="http://cssmenumaker.com/wordpress-plugin-support" target="_blank" class="button-primary">Submit Ticket</a></p>

  <br><br>
  <h2>How do I display my Menu?</h2>
  <p>Once you have created and customized your menu you will want to display it somewhere on your site. There are a couple ways to go about this that are described below.</p>
  
  <h3>Method 1: Theme Location</h3>
  <p>If your theme implements 'Theme Locations' then you will be able to display your menu in one of them. Click the 'Menu Options' tab from the menu edit screen and you will see a select list that contains all possible theme locations. Choose one and then save your menu.</p> 

  <h3>Method 2: Widget</h3>  
  <p>After you have created your menu head over to your <a href="/wp-admin/widgets.php">Wordpress Widgets</a>. On the left hand side you should see the MenuMaker widget. Drag and drop the MenuMaker widget to your desired Widget area. Once you have done this you will see a select list that contains all the menus you have created using MenuMaker. Choose one and then click save.</p>

  <h3>Method 3: Shortcode</h3>
  <p>Shortcodes allow you to print out your menu wherever you want. On the <a href="/wp-admin/edit.php?post_type=cssmenu"> main MenuMaker screen</a> you will see a table of all the menus you have created.  The second column of this table contains the shortcode for each menu. Copy and paste this shortcode into any post and your menu will be printed there.</p> 

</div>