<div id="help-page">
  <h1>Upgrade to MenuMaker Pro</h1>
  <p>Upgrade to MenuMaker Pro and get access to the professional templates and advanced features.</p>
  <p><a href="http://cssmenumaker.com/wordpress-menu-plugin" target="_blank" class="button-primary">Upgrade Now</a></p>

</br>

  <h3>100+ Professionaly Designed Templates</h3>  
  <p>If your theme implements 'Theme Locations' then you will be able to display your menu in one of them. Click the 'Menu Options' tab from the menu edit screen and you will see a select list that contains all possible theme locations. Choose one and then save your menu.</p> 

  <h3>Mobile Ready</h3>  
  <p>After you have created your menu head over to your <a href="/wp-admin/widgets.php">Wordpress Widgets</a>. On the left hand side you should see the MenuMaker widget. Drag and drop the MenuMaker widget to your desired Widget area. Once you have done this you will see a select list that contains all the menus you have created using MenuMaker. Choose one and then click save.</p>

  <h3>Customizable</h3>
  <p>Shortcodes allow you to print out your menu wherever you want. On the <a href="/wp-admin/edit.php?post_type=cssmenu"> main MenuMaker screen</a> you will see a table of all the menus you have created.  The second column of this table contains the shortcode for each menu. Copy and paste this shortcode into any post and your menu will be printed there.</p> 

</div>